name: ai_xmentor_voice
description: Demonstrates how to use the record plugin.
version: 1.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  path: ^1.8.0
  path_provider: ^2.0.1
  audioplayers: ^5.2.0

  flutter:
    sdk: flutter

  record: ^5.0.1
  dart_openai: ^4.1.4
  envied: ^0.5.1
  markdown_widget: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.5.1
  flutter_lints: ^3.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
